ct4-65 : create exercise management & detail page
ClearActionConsistent/ReactJs pull request #119
Opened 2022-12-28 02:00 UTC by Vieup

2023-01-03 10:03 UTC, phantuananh18 approved these changes

2023-01-04 10:27 UTC, tinophan247 commented on src/Routes/index.jsx
> +        path="/exerciseManagement"
Should rename excercise-group-management to avoid confusing with exercise-library-management

2023-01-04 10:28 UTC, tinophan247 commented on src/views/components/Pagination/index.jsx
> -const Paginations = () => {
Please keep the old files

2023-01-04 10:29 UTC, tinophan247 commented on src/views/pages/AdminSite/ExerciseManagement/exerciseDetail.jsx
> +  //   console.log(isShow + "---" + exerciseDatas);
Shoul clear console.log

2023-01-04 10:30 UTC, tinophan247 commented on src/views/pages/AdminSite/ExerciseManagement/exerciseTR.jsx
> +  const createData = (
Should put fake data in constant.js

2023-01-04 10:31 UTC, tinophan247 commented on src/views/pages/AdminSite/ExerciseManagement/exerciseTR.jsx
> +  const exerciseDatas = [
Same with above comment

2023-01-04 10:32 UTC, tinophan247 commented on src/views/pages/AdminSite/ExerciseManagement/exerciseTR.jsx
> +          <TableBody>
TableBody should using map function to optimize code

2023-01-04 10:32 UTC, tinophan247 requested changes
Please help me to resolve all comment thank you

2023-01-04 10:59 UTC, tinophan247 commented on src/App.css
>  }
Please keep the old files

2023-01-04 11:00 UTC, tinophan247 commented on src/views/components/Classes/itemcard.jsx
> -            <div className='flex w-400 items-center border flex-row flex-wrap shadow-xl gap-1 min-h-250 font-tnr hover:bg-gradient-to-b from-orange-100 to-ct4-orange  rounded-lg' onClick={this.handle
Please keep the old files

2023-01-04 11:01 UTC, tinophan247 commented on src/views/components/Modal/ConfirmModal.jsx
> +                : "Are you want to reset password this user ?"}
Rename to deactive and reset password exercise group

2023-01-30 02:58 UTC, closed without merging